repository: kevinlee-k/kevinlee-k
repository_url: https://github.com/kevinlee-k/kevinlee-k

timezone: Asia/SZ
lang: zh_CN

title: 设计狗 · kevinlee-k
alias_en: kevinlee
alias_cn: 设计狗
description: A Navigation Website for kevinlee
keywords: 设计狗, kevinlee, desinger, design,
url: https://github.com/kevinlee-k/kevinlee-k
established_at: "2023-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
